spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.21.27:3306/wxsell?characterEncoding=utf8&useSSL=true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /sell