spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.117:3306/shiro?characterEncoding=utf8&useSSL=true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    database: 2
    host: 192.168.1.167
    port: 6380
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
server:
  port: 8087
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxcde50a847ef1d864
  mpAppSecret: 2e242781221f13761b539a3392267a8a
